// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfUsAf6l76JmS-MJNgZGPsAk7oqRyii7U',
    appId: '1:393938397901:web:7a6ee97ecd4bc6340dd784',
    messagingSenderId: '393938397901',
    projectId: 'crudtutorial-8822b',
    authDomain: 'crudtutorial-8822b.firebaseapp.com',
    storageBucket: 'crudtutorial-8822b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwnYECq2sH3cw3b2CYyr_X0FFp4T7qT0U',
    appId: '1:393938397901:android:7e3b07353ce227e80dd784',
    messagingSenderId: '393938397901',
    projectId: 'crudtutorial-8822b',
    storageBucket: 'crudtutorial-8822b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAifghK5uJaYqWHLOUol2loDdD5PVL4r9Q',
    appId: '1:393938397901:ios:bf04bb396140e8e90dd784',
    messagingSenderId: '393938397901',
    projectId: 'crudtutorial-8822b',
    storageBucket: 'crudtutorial-8822b.appspot.com',
    iosBundleId: 'com.example.crudtutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAifghK5uJaYqWHLOUol2loDdD5PVL4r9Q',
    appId: '1:393938397901:ios:bf04bb396140e8e90dd784',
    messagingSenderId: '393938397901',
    projectId: 'crudtutorial-8822b',
    storageBucket: 'crudtutorial-8822b.appspot.com',
    iosBundleId: 'com.example.crudtutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfUsAf6l76JmS-MJNgZGPsAk7oqRyii7U',
    appId: '1:393938397901:web:883694f68ebe26ef0dd784',
    messagingSenderId: '393938397901',
    projectId: 'crudtutorial-8822b',
    authDomain: 'crudtutorial-8822b.firebaseapp.com',
    storageBucket: 'crudtutorial-8822b.appspot.com',
  );
}
